# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, unique=True)),
                ('url', models.CharField(db_index=True, max_length=300)),
                ('picture', models.ImageField(blank=True, default='', upload_to=b'')),
                ('movie_time', models.CharField(blank=True, default='', max_length=100)),
                ('add_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'banana',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'choice',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=15, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('last_login_date', models.DateTimeField()),
                ('register_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserDiviceId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diviced_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('choice_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterIndexTogether(
            name='uservote',
            index_together=set([('user_id', 'choice_id', 'question_id')]),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Question'),
        ),
    ]
