# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20170913_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice',
            field=models.CharField(choices=[('\u559c\u6b22', '\u4e0d\u559c\u6b22'), ('\u652f\u6301', '\u4e0d\u652f\u6301')], max_length=50),
        ),
    ]
