# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-13 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20170913_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'choice',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice',
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Question'),
        ),
    ]
