# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20170913_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiviceId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diviced_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('choice_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
            ],
        ),
        migrations.AlterIndexTogether(
            name='uservote',
            index_together=set([('user_id', 'choice_id', 'question_id')]),
        ),
    ]
