# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Douban_Top250',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='\u7535\u5f71\u540d\u79f0')),
                ('url', models.CharField(db_index=True, max_length=300, verbose_name='\u7535\u5f71\u94fe\u63a5')),
                ('picture', models.ImageField(blank=True, default='', upload_to=b'', verbose_name='\u5ba3\u4f20\u6d77\u62a5')),
                ('movie_time', models.CharField(blank=True, default='', max_length=100, verbose_name='\u603b\u65f6\u957f')),
                ('add_date', models.DateTimeField(verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('director', models.CharField(max_length=100, verbose_name='\u5bfc\u6f14')),
                ('to_star', models.CharField(max_length=100, verbose_name='\u4e3b\u6f14')),
                ('background', models.CharField(max_length=300, verbose_name='\u7c7b\u578b')),
                ('rating_num', models.IntegerField(default=0, verbose_name='\u8bc4\u5206')),
                ('num_participants', models.CharField(max_length=100, verbose_name='\u53c2\u8bc4\u4eba\u6570')),
            ],
            options={
                'db_table': 'movie_douban_top250',
            },
        ),
    ]
